// Code generated by `tools/functions.php`. DO NOT EDIT.

package compute

// SetFunc0 inserts the given 0-argument function into the [Pad].
func (p *Pad[K, V]) SetFunc0(key K, fn func() V) {
	p.env[key] = &formula[K, V]{fn: func(...V) V { return fn() }}
}

// SetFunc1 inserts the given 1-argument function into the [Pad].
func (p *Pad[K, V]) SetFunc1(key K, fn func(V) V, arg0 K) {
	p.env[key] = &formula[K, V]{
		fn:   func(args ...V) V { return fn(args[0]) },
		args: []K{arg0},
	}
}

// SetFunc2 inserts the given 2-argument function into the [Pad].
func (p *Pad[K, V]) SetFunc2(key K, fn func(V, V) V, arg0, arg1 K) {
	p.env[key] = &formula[K, V]{
		fn:   func(args ...V) V { return fn(args[0], args[1]) },
		args: []K{arg0, arg1},
	}
}

// SetFunc3 inserts the given 3-argument function into the [Pad].
func (p *Pad[K, V]) SetFunc3(key K, fn func(V, V, V) V, arg0, arg1, arg2 K) {
	p.env[key] = &formula[K, V]{
		fn:   func(args ...V) V { return fn(args[0], args[1], args[2]) },
		args: []K{arg0, arg1, arg2},
	}
}

// SetFunc4 inserts the given 4-argument function into the [Pad].
func (p *Pad[K, V]) SetFunc4(key K, fn func(V, V, V, V) V, arg0, arg1, arg2, arg3 K) {
	p.env[key] = &formula[K, V]{
		fn:   func(args ...V) V { return fn(args[0], args[1], args[2], args[3]) },
		args: []K{arg0, arg1, arg2, arg3},
	}
}

// SetFunc5 inserts the given 5-argument function into the [Pad].
func (p *Pad[K, V]) SetFunc5(key K, fn func(V, V, V, V, V) V, arg0, arg1, arg2, arg3, arg4 K) {
	p.env[key] = &formula[K, V]{
		fn:   func(args ...V) V { return fn(args[0], args[1], args[2], args[3], args[4]) },
		args: []K{arg0, arg1, arg2, arg3, arg4},
	}
}

// SetFunc6 inserts the given 6-argument function into the [Pad].
func (p *Pad[K, V]) SetFunc6(key K, fn func(V, V, V, V, V, V) V, arg0, arg1, arg2, arg3, arg4, arg5 K) {
	p.env[key] = &formula[K, V]{
		fn:   func(args ...V) V { return fn(args[0], args[1], args[2], args[3], args[4], args[5]) },
		args: []K{arg0, arg1, arg2, arg3, arg4, arg5},
	}
}

// SetFunc7 inserts the given 7-argument function into the [Pad].
func (p *Pad[K, V]) SetFunc7(key K, fn func(V, V, V, V, V, V, V) V, arg0, arg1, arg2, arg3, arg4, arg5, arg6 K) {
	p.env[key] = &formula[K, V]{
		fn:   func(args ...V) V { return fn(args[0], args[1], args[2], args[3], args[4], args[5], args[6]) },
		args: []K{arg0, arg1, arg2, arg3, arg4, arg5, arg6},
	}
}

// SetFunc8 inserts the given 8-argument function into the [Pad].
func (p *Pad[K, V]) SetFunc8(key K, fn func(V, V, V, V, V, V, V, V) V, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 K) {
	p.env[key] = &formula[K, V]{
		fn:   func(args ...V) V { return fn(args[0], args[1], args[2], args[3], args[4], args[5], args[6], args[7]) },
		args: []K{arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7},
	}
}

// SetFunc9 inserts the given 9-argument function into the [Pad].
func (p *Pad[K, V]) SetFunc9(key K, fn func(V, V, V, V, V, V, V, V, V) V, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 K) {
	p.env[key] = &formula[K, V]{
		fn: func(args ...V) V {
			return fn(args[0], args[1], args[2], args[3], args[4], args[5], args[6], args[7], args[8])
		},
		args: []K{arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8},
	}
}

// SetFunc10 inserts the given 10-argument function into the [Pad].
func (p *Pad[K, V]) SetFunc10(key K, fn func(V, V, V, V, V, V, V, V, V, V) V, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9 K) {
	p.env[key] = &formula[K, V]{
		fn: func(args ...V) V {
			return fn(args[0], args[1], args[2], args[3], args[4], args[5], args[6], args[7], args[8], args[9])
		},
		args: []K{arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9},
	}
}
